"Anti-Aliasing Switcher" application
overte-org/community-apps pull request #7
Opened 2022-07-14 02:08 UTC by AleziaKurdis

Add an "Anti-Aliasing Switcher" application.

Allow different Anti-Aliasing configuration for HMD and Desktop. This application changes automatically the Anti-Aliasing configuration as you put on or remove your VR Headset.

![image](https://user-images.githubusercontent.com/60075796/178882525-ab2f3331-588d-44eb-8b33-895eb79ee7a6.png)

2022-07-14 19:18 UTC, ksuprynowicz requested changes

2022-07-14 19:18 UTC, ksuprynowicz commented on applications/aaswitcher/app-aaSwitcher.js
> +        if (type == "Web" && url.indexOf(APP_URL) != -1) {
Shouldn't it be `type === "Web" && url.indexOf(APP_URL) !== -1`?

2022-07-23 20:06 UTC, daleglass commented
This sounds like a great idea, but maybe we should build this in instead of having it as an add-on?

2022-07-23 20:23 UTC, merged

2022-07-23 22:05 UTC, AleziaKurdis commented
> This sounds like a great idea, but maybe we should build this in instead of having it as an add-on?

I totally agree. This is a prototype / in-between solution. 
Do you see this in the applicative layer (.js) or in the API side ?